name: App Distribution Deploy

# Controls when the workflow will run
on:
  schedule:
    - cron: "20 07 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: check if build is needed and start deploy job on bitrise
        run: |
          if [ "$(git log -1 | grep commit)" != "$(git log -1 --author=mobdev@bd.qatarinsurance.com | grep commit)" ]; then
            echo Cool
          fi;
